### ISSUE TITLE
Bas950 - Presence TODO list

### ISSUE THREAD

**Issue by Bas950** [PreMiD/Presences#1129]
This is my checklist for presences I am going to be making an releasing after presence settings.
**Note:** These are in order of how I will make them

* [x] UpBeatRadio (Recode, requested by partner)
- * [x] Include presence settings

* [x] ListenOnRepeat
- * [ ] Language selector
- * [x] Other settings

* [x] Niantic Wayfarer (Donator Prio) #962 
- * [ ] Language selector

* [x] Vizer #503

* [x] TopFlix #606 

* [x] Pokémon TV #608 
- * [x] Every language
- * [x] watch.
- * [ ] Language Selector

* [x] shinden #611 

* [x] MangaKakalot  #634 

* [x] KissCartoon #660 

* [x] TrueAchievements #663 

* [x] TrueTrophies #664 

* [x] TrueSteamAchievements #665 (Not official banner, contacted TGN for official one)

* [ ] Animes Vision #671 

* [ ] Korean Websites #675 
- * [ ] 아프리카TV
- * [ ] kakaoTV 
- * [ ] SPOTV 
- * [ ] gaonchart
- * [ ] Kocowa
- * [ ] Naver
- * [ ] Gmarket
- * [ ] language selector on all

* [ ] Radio Nintendo #676 

* [ ] Merriam-Webster #686 

* [ ] Pokeflix #689 

* [ ] Hitradio ÖE3 #697 

* [ ] MyDramaList #824 

* [ ] OpenStreetMap #830 

* [ ] radiko (ラジコ) #840 

* [ ] Dumpert #844 

* [ ] Konachan #858 
- * [ ] SFW website
- * [ ] NSFW website

* [ ] bol.com #881 

* [ ] Tetris #917 

* [ ] Wonderfulsubs #919 

* [ ] Just Dance Now #1001 

* [ ] Last.fm #1020 

* [ ] Internet Archives #1023 

* [ ] VIZ #1089 

* [ ] GogoAnime #1122 

* [ ] Fix Discord Time? (FireFox only??) #1133 

* [ ] Plex update (presence settings) #938 

* [ ] Plex Local Server #1137

* [ ] Plex broken in fullscreen #1195 

* [ ] Merge amazon music and amazon presence into 1

* [ ] TuMangaOnline url change to lectortmo

* [ ] pixiv updated their website

* [ ] KissAnime

Have way more on my todo list, but I will make these first.

**Comment by doomlerd** [comment]
VKontakte and Kissanime

**Comment by Bas950** [comment]
> VKontakte and Kissanime

VK Done, added Kissanime to my todo

**Comment by Bas950** [comment]
Removed https://github.com/PreMiD/Presences/issues/644 from todo, since someone else is making it.
