### ISSUE TITLE
Bas950 - Presence TODO list

### ISSUE THREAD

**Issue by Bas950** [PreMiD/Presences#1418]
This is my checklist for presences I am going to be making.
**Note:** These are in order of how I will make them

* [ ] Korean Websites #675 
- * [ ] 아프리카TV
- * [ ] kakaoTV 
- * [ ] SPOTV 
- * [ ] gaonchart
- * [ ] Kocowa
- * [ ] Gmarket
- * [ ] language selector on all

* [ ] Merriam-Webster #686 

* [ ] Pokeflix #689 

* [ ] Hitradio ÖE3 #697 

* [ ] OpenStreetMap #830 

* [ ] radiko (ラジコ) #840 

* [ ] Dumpert #844 

* [ ] Konachan #858 
- * [ ] SFW website
- * [ ] NSFW website

* [ ] Tetris #917 

* [ ] Wonderfulsubs #919 

* [ ] Just Dance Now #1001 

* [ ] Last.fm #1020 

* [ ] Internet Archives #1023 

* [ ] VIZ #1089 

* [ ] GogoAnime #1122 

* [ ] Fix Discord Time? (FireFox only??) #1133 

* [ ] Plex update (presence settings) #938 
Will be added after language selector is released.

* [ ] Merge amazon music and amazon presence into 1

* [ ] TuMangaOnline url change to lectortmo

* [ ] pixiv updated their website

* [ ] KissAnime

* [ ] https://premid.app/store/presences/AnimeFLV broken?
Have way more on my todo list, but I will make these first.

**Comment by QkeleQ10** [comment]
You can remove bol.com #881 #3074

**Comment by Gutito** [comment]
I am looking forward to the last.fm presence. Thanks 🙏
