### ISSUE TITLE
fror - Presence TODO list

### ISSUE THREAD

**Issue by fr0r** [PreMiD/Presences#1449]
yes, i do stuff sometimes

- recode stuff
* [ ] - Nyaa
* [ ] - globoplay
* [ ] - Wikia (Love Live/Bandori)
* [ ] - Uncyclopedia

- to do someday
* [ ] - IGDB #1024 
* [ ] - Canais Globo #1423 
* [ ] - Telecine Play
* [ ] - YTMND
* [ ] - Bandori Party
* [ ] - School Idol Tomodachi
* [ ] - Rate Your Music
* [ ] - VocaDB
* [ ] - Letterboxd #1769

- Add more stuff to porn presences
* [ ] - Pornhub
* [x] - nhentai 
    maybe more soon...
