### ISSUE TITLE
CRUGG - Presence TODO list

### ISSUE THREAD

**Issue by OfficialCRUGG** [PreMiD/Presences#1460]
This is a Todo List of Presences and tweaks/updates to Presences. This List is in no particular order.
* [ ] OnlyHit
  * [ ] Support for Subradios (OnlyHit J-Music, OnlyHit K-Pop & OnlyHit Gold)
  * [ ] Settings
* [ ] Neverthink
* [x] Instagram
  * [x] Fix Post View Bug **(Waiting for PR #1764 to be merged)**
  * [x] Add DM Support **(Waiting for PR #1764 to be merged)**
  * [ ] Settings
  * [ ] Rewrite
* [x] 5Mods
* [x] Anime4You
  * [ ] Support for Players
  * [ ] Settings
* [x] DeepL
* [x] Ecosia
* [x] Gelbooru
* [x] Gitea
  * [ ] Show currently viewed File for Repos
* [x] Kimi no Na wa Wikia
* [x] MyAnimeList
* [x] nekos.life
* [x] NPM Package Registry
* [x] plug.dj
* [x] RealBooru
* [x] Rule34
* [x] Sunshine Live
* [x] taiga Bot
  * [x] Update Presence **(Waiting for PR #1765 to be merged)**
  * [ ] Settings
* [x] Toradora Wikia
  * [ ] Settings to enable/disable English & German Wikia
* [x] ToradorAPI

**Comment by Feestbox** [comment]
also Neverthink ;D

**Comment by OfficialCRUGG** [comment]
> also Neverthink ;D

Added to Todo List! @Feestbox
