### ISSUE TITLE
Gurrman375D TODO List

### ISSUE THREAD

**Issue by Gurrman375** [PreMiD/Presences#1599]
A list of presences I need to develop.
Presence List:
- [ ] SFW
  - [x] AI Dungeon (Completed. https://github.com/PreMiD/Presences/pull/1634)
  - [x] Sparknotes (Completed. https://github.com/PreMiD/Presences/pull/1620)
  - [x] CliffsNotes (Completed. https://github.com/PreMiD/Presences/pull/1665)
  - [x] Otaku-Streamers (Completed. https://github.com/PreMiD/Presences/pull/1723)
  - [x] Anime Heaven (https://github.com/PreMiD/Presences/pull/3304)
  - [ ] Google Voice (In Queue.)
  - [ ] Google Hangouts (In Queue.) 
  - [ ] Bibme (In Queue.)
  - [ ] YGGTorrent (In Queue.)
  - [ ] Mr.Piracy (In Queue.)
  - [ ] Khan Academy (In Queue.)
  - [ ] TrickSplit.io (In Queue. https://github.com/PreMiD/Presences/issues/1678)
  - [ ] JK Anime (In Queue. https://github.com/PreMiD/Presences/issues/1415)
- [ ] NSFW
  - [ ] spnati (In Queue. Trying to put priority fror.)
--------------------------------------------------------------------------------------------------------------
Note:
I'm back baby.

**Comment by Roux55** [comment]
afk ??

**Comment by Gurrman375** [comment]
I've had to fix my repository. Also if you want to discus something with me please use my discord dm's. @Gurr#3014

**Comment by Roux55** [comment]
afk ?
