### ISSUE TITLE
Alanexei TODO List

### ISSUE THREAD

**Issue by Alanexei** [PreMiD/Presences#1741]
*A compiled list of presences that I have chosen to work on in the future, or am already working on.*

__**Presences**__
- [x] [userbenchmark.com](https://userbenchmark.com/)
- [x] [shazam.com](https://shazam.com/)
- [ ] [domains.google.com](https://domains.google.com) #1316 *Waiting For PR*
- [ ] [clickup.com](https://clickup.com/)
