### ISSUE TITLE
Marino TODO List

### ISSUE THREAD

**Issue by marinofranz** [PreMiD/Presences#1750]
TODO List
*Marino*

**Presence(s) Tasks**
* [x] #1726
* [x] [forum.rasb.xyz](http://forum.rasb.xyz/)
* [x] [epicgames.com](https://epicgames.com/)
* [x] [fivem.net](https://fivem.net/)
* [x] #2024

**Bug Tasks**

* [x] Trello
  * [x] Private Board Issue

**Comment by Xzer0o0** [comment]
hi , there is a lot of problems in it , first it doesn't work when the language is not english , for example when the link is "ar.onlinesoccermanager.com" and not "en.onlinesoccermanager.com" it stop working and refuse to show anything , second problem is when you are browsing "career" it write : browsing NOT FOUND. , and i suggest when u are browsing dashboard it write : browsing (LIVERPOOL TEAM) "for exampe" , or it just say : browsing dashboard and not (home page)
thank you.

**Comment by marinofranz** [comment]
Pull request opened for changes: #1775
