### ISSUE TITLE
FelipeSazz TODO List

### ISSUE THREAD

**Issue by Sazzo** [PreMiD/Presences#1751]
I'm going to start doing some things, here's my little TODO List for now.

- [x] Super Animes (#1498) | Completed by Nanashinn - PR: #1778
- [x] Amino Apps (#1083) | Completed - PR: #1800 
- [ ] Yahoo Finance (#1049) | On Hold.
- [ ] Loritta Presence 1.0.2 | On Hold.
