### ISSUE TITLE
Epic Games Store | www.epicgames.com/store

### ISSUE THREAD

**Issue by Isa27-0** [PreMiD/Presences#2004]
**Prerequisites and essential questions**
- [x] Is it a popular site?
- [x] Is the website older than 2 months? 
- [ ] Is the site locked to a specific country/region?
- [ ] Is the site a paid service? (e.g. Netflix, Hulu)
- [ ] Does the website feature NSFW content? (e.g. porn, etc...)
- [ ] Are you a donator/patron?
- [x] Do you acknowledge that coding presences is completely voluntary and may take time for your service to be added regardless of priority?

**What's your Discord username?** 

**What's the name of the service?** Epic Games Store: https://www.epicgames.com/store

**What should the Presence display?** Service name, the name of the game, and the time spent on the page (Similar to the Steam)

**If possible, please provide a logo for the service (512x512 minimum)** 
![Epico games Store (1)](https://user-images.githubusercontent.com/68751594/90957412-b8b53500-e463-11ea-9563-16c48a73718e.png)

**Comment by marinofranz** [comment]
I have added this to my to-do list. #1750
