### ISSUE TITLE
Make a support for Meta Creator Studio and Meta Business Suite

### ISSUE THREAD

**Issue by PhilMinecraft** [PreMiD/Presences#6114]
### Website name

Meta Creator Studio, Meta Business Suite

### Website URL

https://business.facebook.com/creatorstudio, https://business.facebook.com/latest/

### Website logo

https://drive.google.com/file/d/1xjDS4HO6Q2-R1ArcUO_ZL4vS4tfw1wzm/view?usp=sharing https://drive.google.com/file/d/1xjDS4HO6Q2-R1ArcUO_ZL4vS4tfw1wzm/view?usp=sharing

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

Meta Creator Studio is kinda like YouTube Studio, but I can manage all of my media posts (especially videos on Facebook Watch and Instagram Video) on Facebook and Instagram, if I navigate which page I'm in, and what post I'm editing, it should be shown where (but atleast give it some option for it to turn on or off.

Meta Business Suite is same as Meta Creator Studio but it's focused on business like promoting ads on Facebook and Instagram, sharing post on both Facebook (Page and Groups) and Instagram in one place
