### ISSUE TITLE
EPIC NPC MARKETPLACE

### ISSUE THREAD

**Issue by ILnea** [PreMiD/Presences#7134]
### Website name

EPIC NPC MARKETPLACE

### Website URL

https://www.epicnpc.com/

### Website logo

https://img.epicnpc.com/xf/data/avatars/o/452/452232.jpg?1632693535

### Prerequisites

- [ ] It is a paid service
- [ ] It displays NSFW content
- [ ] It is region restricted

### Description

its a Website where we can trade, sell / buy games, in games items etc.
its a good website
